all:
	make -C fill_edges install
	make -C newbars install
	make -C newlines install
	make -C newone install
	make -C newvarlines install
clean:
	make -C fill_edges clean
	make -C newbars clean
	make -C newlines clean
	make -C newone clean
	make -C newvarlines clean
