
#generic Makefile for Linux

OBJ=$(patsubst %.cpp,%.o,$(wildcard *.cpp))
CFLAGS= -std=c++11 -I./include -O2 -DFOR_LINUX `pkg-config acidcam opencv4 glfw3 --cflags` -DNO_SCREEN_GRAB 
LDFLAGS=`pkg-config glfw3 opencv4 acidcam --libs` -lX11

%.o: %.cpp
	$(CXX) $(CFLAGS) $< -c -o $@

acidcamGL: $(OBJ)
	$(CC) src/glad.c -c 
	$(CXX) -std=c++11 -o acidcamGL $(OBJ) glad.o $(LDFLAGS)

all: example

.PHONY: clean
clean:
	rm -f acidcamGL *.o
install:
	cp acidcamGL /usr/local/bin
