
#generic Makefile for Linux

OBJ=$(patsubst %.cpp,%.o,$(wildcard *.cpp))
CFLAGS= -std=c++11 -O2 -DFOR_LINUX `pkg-config acidcam opencv4 glfw3 glew --cflags` -DNO_SCREEN_GRAB 
LDFLAGS=`pkg-config glfw3 glew opencv4 acidcam --libs` -lX11

%.o: %.cpp
	$(CXX) $(CFLAGS) $< -c -o $@

acidcamGL: $(OBJ)
	$(CXX) -std=c++11 -o acidcamGL $(OBJ) $(LDFLAGS)

all: example

.PHONY: clean
clean:
	rm -f acidcamGL *.o
install:
	cp acidcamGL /usr/local/bin
